### ISSUE TITLE
Errore ElasticitySpectraBilayer

### ISSUE THREAD

**Issue by manuela995** [CellMechLab/nanoindentation#5]
Lanciando dal prompt di Anaconda il comando python nano.py compare:

Traceback (most recent call last):
  File "nano.py", line 766, in <module>
    chiaro = NanoWindow()
  File "nano.py", line 39, in __init__
    self.histo_data = pg.PlotCurveItem([0, 0], [
  File "C:\Users\manue\anaconda3\lib\site-packages\pyqtgraph\graphicsItems\PlotCurveItem.py", line 77, in __init__
    self.setData(*args, **kargs)
  File "C:\Users\manue\anaconda3\lib\site-packages\pyqtgraph\graphicsItems\PlotCurveItem.py", line 335, in setData
    self.updateData(*args, **kargs)
  File "C:\Users\manue\anaconda3\lib\site-packages\pyqtgraph\graphicsItems\PlotCurveItem.py", line 385, in updateData
    raise Exception("X and Y arrays must be the same shape--got %s and %s." % (self.xData.shape, self.yData.shape))
Exception: X and Y arrays must be the same shape--got (2,) and (1,).

L'interfaccia del sw non viene aperta. Tutte le librerie indicate nel README sono state installate e l'errore non si presentava con le versioni precedenti del sw.

**Comment by GiuseppeCiccone96** [comment]
Hi, 

it seems like the problem is with pyqtgraph (self.histo_data) on line 39 of the file nano.py. This is likely because the histogram is only supported in newer versions of pyqtgraph. I've just tested it on my laptop, and the GUI launches fine with pyqtgraph 0.11.1. Can you please confirm what version you are using? I would suggest to update to the latest version of pyqtgraph and then try and launch nano.py again. 

Alternatively, you can try and update anaconda (and all its packages) with conda update --all. 

Thank you, 

Giuseppe.

**Comment by manuela995** [comment]
It works now, thank you!

**Comment by GiuseppeCiccone96** [comment]
Great!
